In [2]:
import torch
import numpy as nn
import pandas as pd


In [2]:
a=torch.tensor([3])
print(a)

tensor([3])


In [22]:
b=torch.tensor([
[4,0,1],
[3,1,0],
[4,2,1],
[3,6,2]
])

b.shape

torch.Size([4, 3])

In [25]:
c=torch.tensor([[6,2],[2,6],[4,1]])
c.shape

torch.Size([3, 2])

In [24]:
bc= b @ c
print(bc)

tensor([[28],
        [20],
        [32],
        [38]])


In [5]:
x=torch.tensor([1.0,3,4])
x.dtype

torch.float32

In [12]:
t_n=nn.array([[2.0,4,4],[2,3,4]])
t_n

array([[2., 4., 4.],
       [2., 3., 4.]])

In [13]:
numpy_to_tensor=torch.from_numpy(t_n)

numpy_to_tensor

tensor([[2., 4., 4.],
        [2., 3., 4.]], dtype=torch.float64)

In [ ]:
# From Pandas DataFrame
# Read the data from the CSV file into a DataFrame
df = pd.read_csv('./data.csv')

# Extract the data as a NumPy array from the DataFrame
all_values = df.values


# Convert the DataFrame's values to a PyTorch tensor
tensor_from_df = torch.tensor(all_values)

print("ORIGINAL DATAFRAME:\n\n", df)
print("\nRESULTING TENSOR:\n\n", tensor_from_df)
print("\nTENSOR DATA TYPE:", tensor_from_df)

ORIGINAL DATAFRAME:

    distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47

RESULTING TENSOR:

 tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)

TENSOR DATA TYPE: tensor([13.0900, 32.4100], dtype=torch.float64)


In [34]:
weight=torch.rand(3,2)
weight@torch.rand(2,2)

tensor([[0.5009, 0.7537],
        [0.4012, 0.6923],
        [0.2710, 0.1896]])

In [26]:
arange=torch.arange(1,10, step=1)
arange

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
                  
x.shape == (2, 3, 4, 5, 6)

# x_squeeze=x.unsqueeze(1)
# print(x_squeeze)
# x_squeeze.shape

torch.Size([2, 3])

In [48]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])
tensor_b = torch.tensor([[5, 6],
                         [7, 8]])
a_b=torch.cat((tensor_a,tensor_b),dim=0)
a_b

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [50]:
# Create a 3x4 tensor
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Get a single element at row 1, column 2
single_element_tensor = x[1, 2]

print("\nINDEXING SINGLE ELEMENT AT [1, 2]:", single_element_tensor)
print("-" * 55)

# Get the entire second row (index 1)
second_row = x[1]

print("\nINDEXING ENTIRE ROW [1]:", second_row)
print("-" * 55)

# Last row
last_row = x[-1]

print("\nINDEXING ENTIRE LAST ROW ([-1]):", last_row, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

INDEXING SINGLE ELEMENT AT [1, 2]: tensor(7)
-------------------------------------------------------

INDEXING ENTIRE ROW [1]: tensor([5, 6, 7, 8])
-------------------------------------------------------

INDEXING ENTIRE LAST ROW ([-1]): tensor([ 9, 10, 11, 12]) 



In [51]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Boolean indexing using logical comparisons
mask = x > 6

print("MASK (VALUES > 6):\n\n", mask, "\n")

# Applying Boolean masking
mask_applied = x[mask]

print("VALUES AFTER APPLYING MASK:", mask_applied, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
MASK (VALUES > 6):

 tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]]) 

VALUES AFTER APPLYING MASK: tensor([ 7,  8,  9, 10, 11, 12]) 



In [52]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [54]:
z=torch.tensor([[2,3,4],[2,4,4],[1,2,3],[3,4,4]])
z.shape

torch.Size([4, 3])

In [55]:
matmul=torch.matmul(x,z)
matmul

tensor([[ 21,  33,  37],
        [ 53,  85,  97],
        [ 85, 137, 157]])

In [56]:
matmul.shape

torch.Size([3, 3])

In [57]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1],
                 [2],
                 [3]])

print("TENSOR A:", a)
print("SHAPE:", a.shape)
print("\nTENSOR B\n\n", b)
print("\nSHAPE:", b.shape)
print("-" * 65)

# Apply broadcasting
c = a + b


print("\nTENSOR C:\n\n", c)
print("\nSHAPE:", c.shape, "\n")

TENSOR A: tensor([1, 2, 3])
SHAPE: torch.Size([3])

TENSOR B

 tensor([[1],
        [2],
        [3]])

SHAPE: torch.Size([3, 1])
-----------------------------------------------------------------

TENSOR C:

 tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

SHAPE: torch.Size([3, 3]) 



In [58]:
#Sales data for 3 products over 4 months
sales_data = torch.tensor([[100, 120, 130, 110],   # Product A
                           [ 90,  95, 105, 125],   # Product B
                           [140, 115, 120, 150]    # Product C
                          ], dtype=torch.float32)

print("ORIGINAL SALES DATA:\n\n", sales_data)
print("-" * 45)

### START CODE HERE ###

# 1. Calculate total sales for Product B.
total_sales_product_b = sales_data[1].sum()

# 2. Find months where sales for Product C were > 130.
high_sales_mask_product_c = sales_data[2] >130

# 3. Get sales for Feb and Mar for all products.
sales_feb_mar = sales_data[:, 1:3]

### END CODE HERE ###

print("\nTotal Sales for Product B:                   ", total_sales_product_b)
print("\nMonths with >130 Sales for Product C (Mask): ", high_sales_mask_product_c)
print("\nSales for Feb & Mar:\n\n", sales_feb_mar)

ORIGINAL SALES DATA:

 tensor([[100., 120., 130., 110.],
        [ 90.,  95., 105., 125.],
        [140., 115., 120., 150.]])
---------------------------------------------

Total Sales for Product B:                    tensor(415.)

Months with >130 Sales for Product C (Mask):  tensor([ True, False, False,  True])

Sales for Feb & Mar:

 tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]])


In [6]:
# A batch of 4 grayscale images, each 3x3
image_batch = torch.rand(4, 3, 3)

print("ORIGINAL BATCH SHAPE:", image_batch.shape)
print("-" * 45)

### START CODE HERE ###

# 1. Add a channel dimension at index 1.
image_batch_with_channel = image_batch.unsqueeze(1)

# 2. Transpose the tensor to move the channel dimension to the end.
# Swap dimension 1 (channels) with dimension 3 (the last one).
image_batch_transposed = image_batch.transpose(1,3)

### END CODE HERE ###


print("\nSHAPE AFTER UNSQUEEZE:", image_batch_with_channel.shape)
print("SHAPE AFTER TRANSPOSE:", image_batch_transposed.shape)

ORIGINAL BATCH SHAPE: torch.Size([4, 3, 3])
---------------------------------------------


IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

Exercise 3: Combining and Weighting Sensor Data
You're building an environment monitoring system that uses two sensors: one for temperature and one for humidity. You receive data from these sensors as two separate 1D tensors.

Your task is to:

Concatenate the two tensors into a single 2x5 tensor, where the first row is temperature data and the second is humidity data.
Create a weights tensor torch.tensor([0.6, 0.4]).
Use broadcasting and element-wise multiplication to apply these weights to the combined sensor data. The temperature data should be multiplied by 0.6 and the humidity data by 0.4.
Finally, calculate the weighted average for each time step by summing the weighted values along dim=0 and dividing by the sum of the weights.

In [3]:
# Sensor readings (5 time steps)
temperature = torch.tensor([22.5, 23.1, 21.9, 22.8, 23.5])
humidity = torch.tensor([55.2, 56.4, 54.8, 57.1, 56.8])

print("TEMPERATURE DATA: ", temperature)
print("HUMIDITY DATA:    ", humidity)
print("-" * 45)

### START CODE HERE ###
x=temperature.unsqueeze(0)
print(x)
# 1. Concatenate the two tensors.
# Note: You need to unsqueeze them first to stack them vertically.
combined_data = torch.cat((temperature.unsqueeze(0),humidity.unsqueeze(0)),dim=0)

# 2. Create the weights tensor.
weights = torch.tensor([0.6,0.4])

# 3. Apply weights using broadcasting.
# You need to reshape weights to [2, 1] to broadcast across columns.
weighted_data = combined_data * weights.unsqueeze(1)

# 4. Calculate the weighted average for each time step.
#    (A true average = weighted sum / sum of weights)
weighted_sum = torch.sum(weighted_data)
weighted_average = weighted_sum/torch.sum(weights)

### END CODE HERE ###

print("\nCOMBINED DATA (2x5):\n\n", combined_data)
print("\nWEIGHTED DATA:\n\n", weighted_data)
print("\nWEIGHTED AVERAGE:", weighted_average)

TEMPERATURE DATA:  tensor([22.5000, 23.1000, 21.9000, 22.8000, 23.5000])
HUMIDITY DATA:     tensor([55.2000, 56.4000, 54.8000, 57.1000, 56.8000])
---------------------------------------------
tensor([[22.5000, 23.1000, 21.9000, 22.8000, 23.5000]])

COMBINED DATA (2x5):

 tensor([[22.5000, 23.1000, 21.9000, 22.8000, 23.5000],
        [55.2000, 56.4000, 54.8000, 57.1000, 56.8000]])

WEIGHTED DATA:

 tensor([[13.5000, 13.8600, 13.1400, 13.6800, 14.1000],
        [22.0800, 22.5600, 21.9200, 22.8400, 22.7200]])

WEIGHTED AVERAGE: tensor(180.4000)
